# Generated by Django 3.2.1 on 2021-05-05 07:12

import django.core.validators
import vintage as vintage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_typu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení typu desky')),
                ('typ', models.CharField(blank=True, choices=[('vintage', 'Vintage'),('newschool', 'Newschool'),('pop', 'Pop'),('underground', 'Underground'),('rap', 'Rap')], default='vintage', help_text='Vyberte typ', max_length=20, verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Typ desky',
                'verbose_nam'
                'e_plural': 'Typ desky',
                'ordering': ['oznaceni_typu'],
            },
        ),
        migrations.CreateModel(
            name='Deska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název desky')),
                ('autor', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Autor desky')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis desky')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('hodnoceni', models.IntegerField(blank=True, choices=[(5, 'kvalitni'),(4, 'dobre'),(3, 'prumerne'),(2, 'nekvalitni'),(1, 'neoblibene')], default=3, help_text='Vyberte hodnoceni', max_length=1, verbose_name='Hodnoceni')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='zbozi/%Y/%m/%d/', verbose_name='Cover')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='deska.typ')),
            ],
            options={
                'verbose_name': 'Deska',
                'verbose_name_plural': 'Deska',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
