# Generated by Django 3.2.1 on 2021-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '01 initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deska',
            name='hodnoceni',
            field=models.IntegerField(blank=True, choices=[(5, 'kvalitni'),(4, 'dobre'),(3, 'prumerne'),(2, 'nekvalitni'),(1, 'neoblibene')], default=3, help_text='Vyberte hodnoceni', verbose_name='Hodnoceni'),
        ),
    ]
