# Generated by Django 3.2.1 on 2021-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '02 hodnoceni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deska',
            name='hodnoceni',
            field=models.IntegerField(blank=True, choices=[(5, 'kvalitni'),(4, 'dobre'),(3, 'prumerne'),(2, 'nekvalitni'),(1, 'neoblibene')], default=3, help_text='Vyberte hodnoceni', verbose_name='Hodnoceni'),
        ),
        migrations.AlterField(
            model_name='typ',
            name='oblast',
            field=models.CharField(blank=True, choices=[('vintage', 'Vintage'),('newschool', 'Newschool'),('pop', 'Pop'),('underground', 'Underground'),('rap', 'Rap')], default='vintage', help_text='Vyberte typ', max_length=20, verbose_name='Typ'),
        ),
    ]
